apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    stack: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      stack: voting-app
  template:
    metadata:
      name: db
      labels:
        app: db
        stack: voting-app
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
