apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    stack: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      stack: voting-app
  template:
    metadata:
      name: vote
      labels:
        app: vote
        stack: voting-app
    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: vote
