apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    stack: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      stack: voting-app
  template:
    metadata:
      name: worker
      labels:
        app: worker
        stack: voting-app
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
