apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    stack: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      stack: voting-app
  template:
    metadata:
      name: redis
      labels:
        app: redis
        stack: voting-app
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
