apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    stack: voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
    stack: voting-app
