apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
    stack: voting-app
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 30002
  selector:
    app: result
    stack: voting-app
