apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    stack: voting-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 30001
  selector:
    app: vote
    stack: voting-app
