apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
    stack: voting-app
spec:
  containers:
    - name: db
      image: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
