apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    stack: voting-app
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
      - containerPort: 6379
        name: redis
